### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by esmeleon** [dib-lab/2018-06-27-SpanishSWC#4]
There's a sudden change from Spanish to English at "Pipes" (Under Curricula), maybe we should emphasize it in double star like with \*\*History\** a little farther down in the page. The same could be said for "Scripts" in the same section.

**Comment by esmeleon** [comment]
"Resolving Conflicts" should also be translated, but the line below it seems to already do that.

**Comment by esmeleon** [comment]
The schedule might want to be translated as well.

**Comment by esmeleon** [comment]
Under Text Editor (maybe change to Editorial de Texto?) In "Si accidentalmente te encontraste a find yourself stuck in it", "stuck with it" does not have a good direct translation, but we could rearrange the sentence to say "Si encuentras dificultades," which means directly translates to "If you find difficulties".

**Comment by raynamharris** [comment]
You are quick!! 

Yes, there were some missing translations, but I pull those in from styles-es in this commit (https://github.com/dib-lab/2018-06-27-SpanishSWC/commit/2cad10e49c84f8820d65bf49c416a6207f336fda) 

There were some merge conflicts, so I fixed those in this commit https://github.com/dib-lab/2018-06-27-SpanishSWC/commit/e22155d11d98d1342a5c63039c50aa8cd1486f53

**Comment by raynamharris** [comment]
Let me know if you see anything else in English that needs to be translated.

**Comment by raynamharris** [comment]
Additional missing translations corrected with PR #6
